# Generated by Django 5.2.1 on 2025-06-03 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_price_alter_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
