# Generated by Django 5.2.1 on 2025-06-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
